# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d2812e9632b3bd243622fe82f2875440e6de37bd18b2335a53828b8904235c6389650da9e4c776daecc4a7484a60f5406b2a68945b535a3b6165679c1fa9bb

test:
  secret_key_base: dcec4a3bac606833dc6cd80321694b7f27a815cbd87ee24c3b8525a4a677016fdc4e67bc514bd044d9fb12cbff2e733cff836df395bcf25c811a827f40aec003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
